import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated by{" "}
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          DhiWise
        </a>
      </p>
      <p>Quickly use the links below to navigate through all pages.</p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/prototype" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Prototype
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/viewallpatients" style={{ color: "#87CEFA", textDecoration: "none" }}>
            View All Patients
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/doctordashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Doctor Dashboard
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contactus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Contact Us
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/doctorprofile" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Doctor Profile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/newpatientform" style={{ color: "#87CEFA", textDecoration: "none" }}>
            New Patient Form
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/patientnewprofile" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Patient New Profile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/viewreports" style={{ color: "#87CEFA", textDecoration: "none" }}>
            View Reports
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/uploadxray" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Upload X-ray
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/diagnosisreport" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Diagnosis Report
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/css" style={{ color: "#87CEFA", textDecoration: "none" }}>
            CSS
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/progresstracking" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Progress Tracking
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/treatmentreport" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Treatment Report
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/progressreport" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Progress Report
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;