import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated by{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
      </p>
      <p>Quickly use below links to navigate through all pages.</p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/prototype" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Prototype
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/viewallpatients" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ViewAllPatients
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/doctorsdashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DoctorsDashboard
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contactus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ContactUs
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/doctorprofile" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DoctorProfile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/patientnewprofile" style={{ color: "#87CEFA", textDecoration: "none" }}>
            PatientNewProfile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/viewreports" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ViewReports
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/uploadxray" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UploadXray
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/diagnosisreport" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DiagnosisReport
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/kss" style={{ color: "#87CEFA", textDecoration: "none" }}>
            KSS
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/progresstracking" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProgressTracking
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/treatmentreport" style={{ color: "#87CEFA", textDecoration: "none" }}>
            TreatmentReport
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/progressreport" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProgressReport
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;